org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.19.5
loom_version=1.17.21
fabric_api_version=0.138.4+1.21.10

malilib_version=0.26.8
malilib_version_id=VwmyInJJ

mod_version=0.1.0
maven_group=fr.minlego
archives_base_name=redstone-visualizer
