org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.17.21
fabric_api_version=0.141.6+1.21.11

malilib_version=0.27.20
malilib_version_id=loabWpyU

mod_version=0.1.0
maven_group=fr.minlego
archives_base_name=redstone-visualizer-1.21.11
